"""add fk indexes

Revision ID: 1657675823e1
Revises: bdb61d265314
Create Date: 2026-05-28 07:54:44.661841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1657675823e1'
down_revision: Union[str, Sequence[str], None] = 'bdb61d265314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rep_types_goal_id'), 'rep_types', ['goal_id'], unique=False)
    op.create_index(op.f('ix_reps_goal_id'), 'reps', ['goal_id'], unique=False)
    op.create_index(op.f('ix_reps_rep_type_id'), 'reps', ['rep_type_id'], unique=False)
    op.create_index(op.f('ix_reps_scheduled_date'), 'reps', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reps_scheduled_date'), table_name='reps')
    op.drop_index(op.f('ix_reps_rep_type_id'), table_name='reps')
    op.drop_index(op.f('ix_reps_goal_id'), table_name='reps')
    op.drop_index(op.f('ix_rep_types_goal_id'), table_name='rep_types')
    # ### end Alembic commands ###
