"""add tasks

Unit 14 of the calendar-first redesign. Purely additive: creates `tasks` and its
`taskstatus` enum. No existing table is touched — in particular `reps`, which
holds the rep history.

Revision ID: 8fcad7e710dc
Revises: c994ebad8bfa
Create Date: 2026-09-24 15:02:47.481139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8fcad7e710dc'
down_revision: Union[str, Sequence[str], None] = 'c994ebad8bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerated, then reviewed. Creating the table also creates the
    # `taskstatus` enum type.
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('calendar_event_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'missed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id')
    )
    op.create_index(op.f('ix_tasks_goal_id'), 'tasks', ['goal_id'], unique=False)
    op.create_index(op.f('ix_tasks_scheduled_date'), 'tasks', ['scheduled_date'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_tasks_scheduled_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_goal_id'), table_name='tasks')
    op.drop_table('tasks')
    # Autogenerate leaves this out. Dropping a table does not drop the enum type it
    # created, so without this line a downgrade followed by an upgrade fails with
    # "type taskstatus already exists".
    sa.Enum(name='taskstatus').drop(op.get_bind(), checkfirst=True)
