"""init

Revision ID: bdb61d265314
Revises: 
Create Date: 2026-05-28 07:51:47.830687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bdb61d265314'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'archived', name='goalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rep_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('criterion', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_floor', sa.Integer(), nullable=True),
    sa.Column('weekly_target', sa.Integer(), nullable=True),
    sa.Column('is_first_rep', sa.Boolean(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='reptypestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rep_type_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'missed', name='repstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['rep_type_id'], ['rep_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reps')
    op.drop_table('rep_types')
    op.drop_table('goals')
    # ### end Alembic commands ###
