"""add weekly_summaries

Revision ID: c994ebad8bfa
Revises: 1657675823e1
Create Date: 2026-09-07 21:32:30.209415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c994ebad8bfa'
down_revision: Union[str, Sequence[str], None] = '1657675823e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('rep_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_summaries_week_start_date'), 'weekly_summaries', ['week_start_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_summaries_week_start_date'), table_name='weekly_summaries')
    op.drop_table('weekly_summaries')
    # ### end Alembic commands ###
